window.IconLiquidConfig = Object.freeze({
  productPrices: {
    'Limoncello 100ml': 40,
    'Mango Ice 100ml': 46,
    'Wild Tobacco 100ml': 40,
    'Caramel Vanilla 100ml': 40,
    'Ice Berry 100ml': 46,
    'Green Apple 100ml': 40,
    'Cola Lemon 100ml': 40,
    'Blue Razz Ice 100ml': 46,
    'Strawberry Kiwi 100ml': 46,
    'Grape Ice 100ml': 40,
    'Peach Ice 100ml': 46,
    'Pistachio Cream 100ml': 40,
    'Vanilla Custard 100ml': 53,
    'Cola Ice 100ml': 40,
    'Personalizzabile 100ml': 40,
    'Astroberry 100ml': 50
  },
  productOldPrices: {
    'Limoncello 100ml': 50,
    'Mango Ice 100ml': 56,
    'Wild Tobacco 100ml': 50,
    'Caramel Vanilla 100ml': 50,
    'Ice Berry 100ml': 56,
    'Green Apple 100ml': 50,
    'Cola Lemon 100ml': 50,
    'Blue Razz Ice 100ml': 56,
    'Strawberry Kiwi 100ml': 56,
    'Grape Ice 100ml': 50,
    'Peach Ice 100ml': 56,
    'Pistachio Cream 100ml': 50,
    'Vanilla Custard 100ml': 63,
    'Cola Ice 100ml': 50,
    'Personalizzabile 100ml': 50
  },
  pinkSparkleProducts: {
    'Vanilla Custard 100ml': true
  },
  defaultReviews: [
    { name: 'Marco R.', stars: 5, text: 'Preso Mango Ice, davvero buono. Aroma forte e non stanca.', date: '12 Febbraio 2026' },
    { name: 'Luca B.', stars: 5, text: 'Blue Razz Ice top. Fresco al punto giusto.', date: '8 Febbraio 2026' },
    { name: 'Andrea F.', stars: 5, text: 'Ottimo servizio, ho scritto su WhatsApp e mi hanno risposto subito.', date: '5 Febbraio 2026' },
    { name: 'Giuseppe M.', stars: 5, text: 'Wild Tobacco molto realistico, finalmente un tabaccoso serio.', date: '2 Febbraio 2026' },
    { name: 'Davide S.', stars: 5, text: 'Strawberry Kiwi buonissimo, lo sto usando tutti i giorni.', date: '29 Gennaio 2026' },
    { name: 'Simone L.', stars: 5, text: 'Spedizione veloce e prodotto fatto bene.', date: '26 Gennaio 2026' },
    { name: 'Alessandro P.', stars: 5, text: 'Pistachio Cream veramente cremoso, si sente la qualità.', date: '24 Gennaio 2026' },
    { name: 'Francesco T.', stars: 5, text: 'Prezzo onesto e liquido fatto bene.', date: '21 Gennaio 2026' },
    { name: 'Matteo C.', stars: 5, text: "Ice Berry molto fresco, perfetto per l'estate.", date: '18 Gennaio 2026' },
    { name: 'Gabriele D.', stars: 5, text: 'Ordine semplice da fare, tutto chiaro.', date: '15 Gennaio 2026' },
    { name: 'Daniele V.', stars: 4, text: 'Cola Lemon molto buono. Ho aspettato 3 giorni per la consegna ma alla fine è arrivato tutto perfetto.', date: '13 Gennaio 2026' },
    { name: 'Stefano N.', stars: 4, text: "Vanilla Custard ottimo gusto. Un po' di ritardo nella consegna ma niente di grave.", date: '10 Gennaio 2026' },
    { name: 'Antonio G.', stars: 4, text: 'Green Apple molto buono. Pensavo arrivasse prima, ma il prodotto vale.', date: '7 Gennaio 2026' },
    { name: 'Riccardo Z.', stars: 4, text: 'Ho fatto un mix personalizzato ed è venuto bene. Ho dovuto aspettare qualche giorno in più.', date: '4 Gennaio 2026' },
    { name: 'Fabio E.', stars: 4, text: 'Liquido ottimo. Consegna leggermente lenta ma servizio buono.', date: '30 Dicembre 2025' },
    { name: 'Nicola R.', stars: 5, text: 'Peach Ice molto equilibrato, lo consiglio.', date: '28 Dicembre 2025' },
    { name: 'Paolo A.', stars: 5, text: 'Servizio serio, rispondono subito ai messaggi.', date: '24 Dicembre 2025' },
    { name: 'Marco T.', stars: 5, text: 'Ottimo rapporto qualità prezzo.', date: '20 Dicembre 2025' },
    { name: 'Christian B.', stars: 5, text: 'Liquido fatto bene, aroma intenso.', date: '17 Dicembre 2025' },
    { name: 'Roberto F.', stars: 5, text: 'Cola Ice molto fedele al gusto cola.', date: '14 Dicembre 2025' },
    { name: 'Emanuele P.', stars: 5, text: 'Blue Razz Ice il mio preferito.', date: '10 Dicembre 2025' },
    { name: 'Lorenzo C.', stars: 5, text: 'Prodotto arrivato in poco tempo, tutto perfetto.', date: '7 Dicembre 2025' },
    { name: 'Andrea S.', stars: 5, text: 'Mango Ice davvero forte come aroma.', date: '3 Dicembre 2025' },
    { name: 'Giovanni L.', stars: 5, text: 'Ho preso più gusti e sono tutti buoni.', date: '30 Novembre 2025' },
    { name: 'Davide R.', stars: 5, text: 'Servizio affidabile, comprerò ancora.', date: '27 Novembre 2025' },
    { name: 'Matteo P.', stars: 5, text: 'Strawberry Kiwi molto piacevole.', date: '23 Novembre 2025' },
    { name: 'Federico D.', stars: 5, text: 'Qualità alta, si sente la differenza.', date: '20 Novembre 2025' },
    { name: 'Alessio M.', stars: 5, text: 'Personalizzabile comodissimo, fatto su misura.', date: '17 Novembre 2025' },
    { name: 'Simone G.', stars: 5, text: 'Prezzo giusto e liquido buono.', date: '13 Novembre 2025' },
    { name: 'Gianluca B.', stars: 5, text: 'Consigliato, tutto perfetto.', date: '10 Novembre 2025' }
  ]
});
